export default {
  docs: [
    {
      type: 'category',
      label: '基础教程',
      collapsed: false,
      items: ['basic/intro', 'basic/quick-start', 'basic/core-concepts', 'basic/widget-basics'],
    },
    {
      type: 'category',
      label: '进阶指南',
      collapsed: false,
      items: [
        'advanced/lifecycle',
        'advanced/update-mechanism',
        'advanced/custom-widget',
        'advanced/events',
        'advanced/devtools',
        'advanced/performance',
        'advanced/testing',
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: true,
      items: [
        'api/api-index',
        {
          type: 'category',
          label: 'Widgets',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/widgets',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Demo 例子',
      collapsed: true,
      items: ['demo/mindmap'],
    },
    {
      type: 'category',
      label: '其他资源',
      collapsed: true,
      items: ['meta/faq', 'meta/test-overview', 'meta/test-component'],
    },
  ],
};
