export default {
  docs: [
    {
      type: 'category',
      label: '快速入门',
      collapsed: false,
      items: ['basic/intro', 'basic/quick-start', 'basic/core-concepts', 'basic/widget-basics'],
    },
    {
      type: 'category',
      label: '核心框架',
      collapsed: false,
      items: [
        'core/architecture',
        'core/lifecycle',
        'core/update-mechanism',
        'core/view-transform',
        'core/events',
      ],
    },
    {
      type: 'category',
      label: '进阶指南',
      collapsed: false,
      items: [
        'advanced/custom-widget',
        'advanced/performance',
        'advanced/devtools',
        'advanced/testing',
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: true,
      items: [
        'api/api-index',
        'api/utils',
        {
          type: 'category',
          label: 'Widgets',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/widgets',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Demo 例子',
      collapsed: true,
      items: ['demo/mindmap', 'demo/interactive-counter', 'demo/widget-gallery', 'demo/swiper'],
    },
    {
      type: 'category',
      label: '其他资源',
      collapsed: true,
      items: ['meta/faq', 'meta/test-overview', 'meta/test-component', 'meta/test-benchmark'],
    },
  ],
};
