export default {
  docs: [
    {
      type: 'category',
      label: '快速入门',
      collapsed: false,
      items: [
        'basic/intro',
        'basic/quick-start',
        'basic/core-concepts',
        'basic/widget-basics',
        'basic/configuration',
      ],
    },
    {
      type: 'category',
      label: '核心框架',
      collapsed: false,
      items: [
        'core/architecture',
        'core/lifecycle',
        'core/update-mechanism',
        'core/view-transform',
        'core/events',
      ],
    },
    {
      type: 'category',
      label: '进阶指南',
      collapsed: false,
      items: [
        'advanced/custom-widget',
        'advanced/performance',
        'advanced/devtools',
        'advanced/testing',
        'advanced/theme',
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      collapsed: true,
      items: [
        'api/preview',
        'api/utils',
        {
          type: 'category',
          label: '核心组件',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/widgets',
            },
          ],
        },
        {
          type: 'category',
          label: 'UI 组件',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/comp',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Demo 例子',
      collapsed: true,
      items: ['demo/mindmap', 'demo/spreadsheet'],
    },
    {
      type: 'category',
      label: '其他资源',
      collapsed: true,
      items: ['meta/faq', 'meta/math-test', 'meta/test-component', 'meta/test-benchmark'],
    },
    {
      type: 'category',
      label: '报告',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'reports',
        },
      ],
    },
  ],
};
